// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwzsmfoxjfexodgblzfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3enNtZm94amZleG9kZ2JsemZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzk2MDksImV4cCI6MjA3MDgxNTYwOX0.qvfliCVQ6iFPmc6w0fC5i8Je9omBpNwlyN23EyfyOgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});